using UnityEngine;
using UnityEngine.Tilemaps;
using System.Collections.Generic;

[RequireComponent(typeof(TilemapRenderer))]
public class TileLightingManager : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private Tilemap surfaceTilemap;
    
    [Header("Light Map Settings")]
    [SerializeField] private int mapWidth = 256;   // Размер карты освещения по X
    [SerializeField] private int mapHeight = 256;  // Размер карты освещения по Y

    [Header("Light Settings")]
    [SerializeField] private float surfaceLight = 1f;
    [SerializeField] private float minLight = 0.15f;
    [SerializeField] private float verticalDecay = 0.92f;
    [SerializeField] private float horizontalSpread = 0.85f;
    [SerializeField] private int maxHorizontalSteps = 10;

    [Header("Performance")]
    [SerializeField] private bool autoRecalculate = true;
    [SerializeField] private float recalculateDelay = 0.1f;

    private TilemapRenderer tilemapRenderer;
    private MaterialPropertyBlock propBlock;
    private Texture2D lightMap; // 👈 Создаётся автоматически
    private float[,] lightValues;
    private bool isDirty = false;
    private float dirtyTimer = 0f;
    private Dictionary<Vector3Int, bool> solidCache = new Dictionary<Vector3Int, bool>();
    private Vector3 worldOffset;

    private void Awake()
    {
        tilemapRenderer = GetComponent<TilemapRenderer>();
        propBlock = new MaterialPropertyBlock();

        if (surfaceTilemap == null) surfaceTilemap = GetComponent<Tilemap>();
        
        mapWidth = Mathf.Max(1, mapWidth);
        mapHeight = Mathf.Max(1, mapHeight);

        // 🔥 Создаём текстуру программно. Она СРАЗУ доступна для записи (readable = true)
        lightMap = new Texture2D(mapWidth, mapHeight, TextureFormat.RGBA32, false)
        {
            filterMode = FilterMode.Point,
            wrapMode = TextureWrapMode.Clamp,
            name = "AutoGeneratedLightMap"
        };

        lightValues = new float[mapWidth, mapHeight];

        // Расчёт границ тайлмапа в мировых координатах
        BoundsInt bounds = surfaceTilemap.cellBounds;
        Vector2 cellSize = new Vector2(surfaceTilemap.cellSize.x, surfaceTilemap.cellSize.y);
        Vector3 minWorld = surfaceTilemap.CellToWorld(bounds.min);
        float worldWidth = bounds.size.x * cellSize.x;
        float worldHeight = bounds.size.y * cellSize.y;
        worldOffset = minWorld;

        // Передаём данные в шейдер
        tilemapRenderer.GetPropertyBlock(propBlock);
        propBlock.SetVector("_WorldBounds", new Vector4(minWorld.x, minWorld.y, worldWidth, worldHeight));
        propBlock.SetTexture("_LightMap", lightMap);
        tilemapRenderer.SetPropertyBlock(propBlock);

        CacheSolidTiles();
        RecalculateLighting();

        if (autoRecalculate) Tilemap.tilemapTileChanged += OnTileChanged;
    }

    private void OnDestroy() => Tilemap.tilemapTileChanged -= OnTileChanged;

    private void Update()
    {
        if (isDirty) {
            dirtyTimer += Time.deltaTime;
            if (dirtyTimer >= recalculateDelay) {
                RecalculateLighting();
                isDirty = false;
                dirtyTimer = 0f;
            }
        }
    }

    private void OnTileChanged(Tilemap tm, Tilemap.SyncTile[] syncTiles) {
        if (tm == surfaceTilemap) MarkDirty();
    }

    public void MarkDirty() {
        isDirty = true;
        dirtyTimer = 0f;
        CacheSolidTiles();
    }

    private void CacheSolidTiles() {
        solidCache.Clear();
        if (surfaceTilemap == null) return;
        BoundsInt b = surfaceTilemap.cellBounds;
        for (int x = b.xMin; x <= b.xMax; x++)
            for (int y = b.yMin; y <= b.yMax; y++) {
                Vector3Int p = new Vector3Int(x, y, 0);
                solidCache[p] = surfaceTilemap.GetTile(p) != null;
            }
    }

    public void RecalculateLighting()
    {
        for (int x = 0; x < mapWidth; x++)
            for (int y = 0; y < mapHeight; y++)
                lightValues[x, y] = minLight;

        for (int tx = 0; tx < mapWidth; tx++) {
            float wx = tx * surfaceTilemap.cellSize.x + worldOffset.x;
            for (int ty = mapHeight - 1; ty >= 0; ty--) {
                float wy = ty * surfaceTilemap.cellSize.y + worldOffset.y;
                Vector3Int grid = surfaceTilemap.WorldToCell(new Vector3(wx, wy, 0));
                if (!IsSolidAt(grid)) {
                    lightValues[tx, ty] = surfaceLight;
                    PropagateVertical(tx, ty - 1, wx);
                    break;
                }
            }
        }

        for (int x = 0; x < mapWidth; x++)
            for (int y = 0; y < mapHeight; y++)
                if (lightValues[x, y] > minLight + 0.1f)
                    PropagateHorizontal(x, y);

        UpdateTexture();
    }

    private void PropagateVertical(int tx, int startTy, float wx) {
        float light = surfaceLight;
        for (int ty = startTy; ty >= 0; ty--) {
            float wy = ty * surfaceTilemap.cellSize.y + worldOffset.y;
            if (IsSolidAt(surfaceTilemap.WorldToCell(new Vector3(wx, wy, 0))))
                light *= verticalDecay * 0.5f;
            else
                light *= verticalDecay;

            light = Mathf.Max(light, minLight);
            if (light > lightValues[tx, ty]) lightValues[tx, ty] = light;
            if (light <= minLight + 0.01f) break;
        }
    }

    private void PropagateHorizontal(int sx, int sy) {
        float baseL = lightValues[sx, sy];
        float wy = sy * surfaceTilemap.cellSize.y + worldOffset.y;

        for (int dir = -1; dir <= 1; dir += 2) {
            for (int step = 1; step <= maxHorizontalSteps; step++) {
                int tx = sx + dir * step;
                if (tx < 0 || tx >= mapWidth) break;
                float wx = tx * surfaceTilemap.cellSize.x + worldOffset.x;
                if (IsSolidAt(surfaceTilemap.WorldToCell(new Vector3(wx, wy, 0)))) break;

                float l = baseL * Mathf.Pow(horizontalSpread, step);
                l = Mathf.Max(l, minLight);
                if (l > lightValues[tx, sy]) lightValues[tx, sy] = l;
            }
        }
    }

    private void UpdateTexture() {
        if (lightMap == null) return;
        
        Color32[] pixels = new Color32[mapWidth * mapHeight];
        for (int x = 0; x < mapWidth; x++)
            for (int y = 0; y < mapHeight; y++)
                pixels[y * mapWidth + x] = new Color32(
                    (byte)(Mathf.Clamp01(lightValues[x, y]) * 255), 255, 255, 255);

        lightMap.SetPixels32(pixels);
        lightMap.Apply(false, false);
    }

    private bool IsSolidAt(Vector3Int p) => solidCache.TryGetValue(p, out bool v) && v;
    public void OnTileBroken(Vector3Int gp) => MarkDirty();
}